Feat/commentapp
GB-Agile-4/gb_habr pull request #29
Opened 2022-06-24 19:07 UTC by AlexMomot-717

2022-06-24 21:59 UTC, IgoryanM requested changes

2022-06-24 21:59 UTC, IgoryanM commented on adminapp/admin.py
> +admin.site.register(Article)
зачем вниз это?

2022-06-24 21:59 UTC, IgoryanM commented on commentapp/migrations/0001_initial.py
> +# Generated by Django 4.0.4 on 2022-06-22 15:36
миграции не нужны

2022-06-25 02:49 UTC, AlexMomot-717 commented on adminapp/admin.py
> +admin.site.register(Article)
🤔 изменю

2022-06-25 02:51 UTC, AlexMomot-717 commented on commentapp/migrations/0001_initial.py
> +# Generated by Django 4.0.4 on 2022-06-22 15:36
Проворонила)...включу в gitignore

2022-06-25 06:37 UTC, AlexMomot-717 commented on adminapp/admin.py
> +admin.site.register(Article)
done

2022-06-25 06:37 UTC, AlexMomot-717 commented on commentapp/migrations/0001_initial.py
> +# Generated by Django 4.0.4 on 2022-06-22 15:36
done

2022-06-25 09:05 UTC, IgoryanM approved these changes

2022-06-25 09:30 UTC, merged