Fix/fix comments
GB-Agile-4/gb_habr pull request #46
Opened 2022-07-03 17:56 UTC by AlexMomot-717

2022-07-04 20:32 UTC, IgoryanM commented on articleapp/urls.py
> +    # path('edit/<int:pk>/', ArticleUpdateView.as_view(), name='edit'),
что тут не так?

2022-07-04 20:36 UTC, IgoryanM commented on gb_habr/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
Если меняешь только для себя, то тогда не включай это в коммит

2022-07-04 20:40 UTC, IgoryanM requested changes

2022-07-04 20:40 UTC, IgoryanM commented on articleapp/urls.py
> +    # path('edit/<int:pk>/', ArticleUpdateView.as_view(), name='edit'),
что тут не так?

2022-07-04 20:40 UTC, IgoryanM commented on gb_habr/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
Если меняешь только для себя, то тогда не включай это в коммит

2022-07-04 20:40 UTC, IgoryanM commented on articleapp/views.py
> -from django.shortcuts import render, get_object_or_404, redirect
много удалений - это точно работает?)

2022-07-05 05:49 UTC, AlexMomot-717 commented on articleapp/urls.py
> +    # path('edit/<int:pk>/', ArticleUpdateView.as_view(), name='edit'),
fixes done

2022-07-05 05:49 UTC, AlexMomot-717 commented on articleapp/urls.py
> +    # path('edit/<int:pk>/', ArticleUpdateView.as_view(), name='edit'),
fixes done

2022-07-05 05:50 UTC, AlexMomot-717 commented on gb_habr/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
исправлено

2022-07-05 05:51 UTC, AlexMomot-717 commented on articleapp/views.py
> -from django.shortcuts import render, get_object_or_404, redirect
исправлено

2022-07-05 20:44 UTC, IgoryanM approved these changes

2022-07-06 11:56 UTC, closed without merging